In [4]:
import numpy as np

In [5]:
mylist = [1,2,3,4]
mylist1 = np.array(mylist)

In [6]:
mylist1

array([1, 2, 3, 4])

In [7]:
mylist2 = [10,11,12,13]

In [8]:
mylist2

[10, 11, 12, 13]

In [9]:
mylists = [mylist1, mylist2]

In [10]:
mylists

[array([1, 2, 3, 4]), [10, 11, 12, 13]]

In [11]:
my_array = np.array(mylists)

In [12]:
my_array

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [13]:
my_array.shape

(2, 4)

In [14]:
my_array.dtype

dtype('int64')

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros(5).dtype

dtype('float64')

In [17]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [22]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])